defaults:
  - _self_
  - model: resnext
  - dataset: 48_classes_supervised
  - optim: SGD
  - loss_fn: cross_entropy

epochs: 300

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  unlabelled_dataset_path: ${dataset.unlabelled_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  aug_transform: ${dataset.aug_transform}
  aug_transform_strong: ${dataset.aug_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/model.pt

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true

T1 : 1
T2 : 1
af : 1
unlabelled_total : 6000
confidence: 0.95

holes: 1
cutoutlength: 40
loss_counter: 3