_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.RandomVerticalFlip
  - _target_: torchvision.transforms.RandomGrayscale
    p: 0.3
  - _target_: torchvision.transforms.RandomApply
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.8
      contrast: 0.8
      saturation: 0.8
      hue: 0.2
    p: 0.4
  - _target_: torchvision.transforms.RandomApply
    -_target_: torchvision.transforms.GaussianBlur
      kernel_size: 3
    p: 0.2
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 224
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]