_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.RandomVerticalFlip
  - _target_: torchvision.transforms.RandomChoice
    transforms: 
      - _target_: torchvision.transforms.GaussianBlur
        kernel_size: 7
      - _target_: torchvision.transforms.GaussianBlur
        kernel_size: 13
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]